version: '3.8'
services:
  laravel:
    build: .
    image: crud
    container_name: laravel
    ports:
      - '80:80'
      - '5173:5173'
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    networks:
      - default
    depends_on:
      - mongodb
  mongodb:
    image: 'mongo:4.4'
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MONGO_INITDB_DATABASE: '${DB_DATABASE}'
    volumes:
      - 'mongodb:/data/db'
networks:
  default:
    driver: bridge
volumes:
  vendor:
  mongodb:
    driver: local